### ISSUE TITLE
Error when shuffle dataset

### ISSUE THREAD

**Issue by xishazgh** [lisa-groundhog/GroundHog#34]
Hi,

I'm new on neural networks and GroundHog.  Now I am trying to but I get this error:

python shuffle-hdf5.py binarized_text.en.h5 binarized_text.zn.h5 binarized_text.en.shuf.h5 binarized_text.zn.shuf.h5
Data len: 2208739
Shuffled
. . . . . . . . . 100000 . . . . . . . . . 200000 . . . . . . . . . 300000 . . . . . . . . . 400000 . . . . . . . . . 500000 . . . . . . . . . 600000 . . . . . . . . . 700000 . . . . . . . . . 800000 . . . . . . . . . 900000 . . . . .
Traceback (most recent call last):
  File "shuffle-hdf5-1.py", line 68, in <module>
    pos = indices_in[fi][ii]['pos']
  File "C:\Python27\lib\site-packages\tables\table.py", line 2119, in __getitem__
    raise IndexError("Index out of range")
IndexError: Index out of range

Could anyone help me with it?

**Comment by nouiz** [comment]
Hi,

GroundHog isn't actively developped for now. We are more working on blocks.
There is a PR to document it:

(https://github.com/mila-udem/blocks-examples/pull/20).


Blocks isn't completly ready to replace all GroundHog feature yet.

But I try guess a few reason for your errors:

- old pytables version
- the original file is truncated/corrupt

This could explain that. Can you check them?
