### ISSUE TITLE
ValueError: Cannot construct a ufunc with more than 32 operands

### ISSUE THREAD

**Issue by zhangdongxu** [lisa-groundhog/GroundHog#44]
This error happens when using search mode. But program can still run. Does it impact the compiling of attention framework?

2016-01-21 17:59:38,114: groundhog.trainer.SGD_adadelta: DEBUG: Constructing grad function
2016-01-21 17:59:39,072: groundhog.trainer.SGD_adadelta: DEBUG: Compiling grad function
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x3717f50>
2016-01-21 18:01:21,598: theano.gof.opt: ERROR: SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x3717f50>
ERROR (theano.gof.opt): Traceback:
2016-01-21 18:01:21,598: theano.gof.opt: ERROR: Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/nfs/nlphome/nlp/tools/python27/root/usr/lib64/python2.7/site-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/nfs/nlphome/nlp/tools/python27/root/usr/lib64/python2.7/site-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, _args, *_kwargs)
  File "/nfs/nlphome/nlp/tools/python27/root/usr/lib64/python2.7/site-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/nfs/nlphome/nlp/tools/python27/root/usr/lib64/python2.7/site-packages/theano/tensor/opt.py", line 5433, in local_fuse
    n = OP(C)(*inputs).owner
  File "/nfs/nlphome/nlp/tools/python27/root/usr/lib64/python2.7/site-packages/theano/tensor/elemwise.py", line 496, in **init**
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 40 and outputs = 1)

2016-01-21 18:01:21,648: theano.gof.opt: ERROR: Traceback (most recent call last):
  File "/nfs/nlphome/nlp/tools/python27/root/usr/lib64/python2.7/site-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/nfs/nlphome/nlp/tools/python27/root/usr/lib64/python2.7/site-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, _args, *_kwargs)
  File "/nfs/nlphome/nlp/tools/python27/root/usr/lib64/python2.7/site-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/nfs/nlphome/nlp/tools/python27/root/usr/lib64/python2.7/site-packages/theano/tensor/opt.py", line 5433, in local_fuse
    n = OP(C)(*inputs).owner
  File "/nfs/nlphome/nlp/tools/python27/root/usr/lib64/python2.7/site-packages/theano/tensor/elemwise.py", line 496, in **init**
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 40 and outputs = 1)

**Comment by nouiz** [comment]
Update Theano to the development version.

Le ven. 22 janv. 2016 00:08, zhangdongxu notifications@github.com a
écrit :

**Comment by zhangdongxu** [comment]
Thank you. Development version works.
